version: '3'

services:
  app:
    container_name: cadmus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27018:27017"
    volumes:
      - mernjobs:/data/db

volumes:
  mernjobs: